### ISSUE TITLE
SERVER-ENHANCEMENT - Sorting & Filtering API

### ISSUE THREAD

**Issue by DotFreelance** [kennyhong/Eventus#15]
As a [_Front End or App_] developer I want to be able to sort, filter and paginate my results through the API so that I can provide a better user experience.

Requirements:
- Add whatever is necessary to implement sorting and filtering in the controller: use [scopes](https://laravel.com/docs/4.2/eloquent#query-scopes) where necessary
- Add the ability to [paginate](https://laravel.com/docs/5.3/pagination)
- These must have an API hook, usually a GET variable like `/api/events?page=2` or `/api/events?sortBy=name&order=desc`
- These API hooks must be [documented](https://github.com/kennyhong/Eventus-Server/wiki)

Estimated time:  
8 Developer Hours

**Comment by JeffreyThiessen** [comment]
https://github.com/kennyhong/Eventus-Server/tree/Filtering

**Comment by DotFreelance** [comment]
Requests:
**Sorting**
- Events by DATE ( by default )
- Services by NAME or COST ( NAME by default )
- ServiceTags by NAME ( by default )

ASCENDING and DESCENDING for each

**Comment by DotFreelance** [comment]
Note: we are skipping Pagination in this task because it isn't part of the MVP. It was mistakenly added as non-optional requirement to this card. This was intended to be optional, and is being omitted.
