### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by kennyhong** [kennyhong/Eventus#6]
Due Date: February 7th

Description: 
Your team's proposal will outline the scope of your project. It will start out with a brief elevator pitch made to the instructor, in class. After discussion and refinement, you will submit a formal proposal by the due date given above.

The formal proposal will include broad user stories for your entire project, prioritized so that the highest-priority stories will form your minimum viable product. It will also include technical details describing how your project will use all of the required technologies.

By the time the proposal is handed in you must have a live repository and project tracking system. As part of your proposal you must include all information needed to access your repository and tracking system.

**Comment by kncdev132** [comment]
# Todo:

- broad user stories for your entire project
	- mvp (from stories)
- technical details describing how your project will use all of the required technologies


# Stories:

## MVP:
- users to save previous session data
- events
- services (part of events?)
- filtering (services?) by criteria
- sorting (services?) by criteria

## Additional:
- booking system of services
- invoice
- cost breakdown of an event
- reccomendations by budget (tied to filtering)
- preset frameworks for events
- iOS notification
- could qr codes be useful? (could be iOS specific)

# Tech:
- AWS
- REST API
- MySQL
- PHP
- Swift 3
- Java
- jQuery
- Angular
- Node.js

(Note: this is relevant to #11)
